// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TheRooms.Data;

namespace TheRooms.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20170829101552_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheRooms.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoomFromId");

                    b.Property<int>("RoomToId");

                    b.HasKey("Id");

                    b.HasIndex("RoomFromId");

                    b.HasIndex("RoomToId");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("TheRooms.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<string>("Name");

                    b.Property<string>("Task");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TheRooms.Models.Door", b =>
                {
                    b.HasOne("TheRooms.Models.Room", "RoomFrom")
                        .WithMany()
                        .HasForeignKey("RoomFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TheRooms.Models.Room", "RoomTo")
                        .WithMany()
                        .HasForeignKey("RoomToId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
